# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev43+g1ba3762.d20230718'
__version_tuple__ = version_tuple = (0, 1, 'dev43', 'g1ba3762.d20230718')
